[package]
name = "texto_desenho"
version = "0.3.2"
edition = "2018"


[dependencies]
#utilitarios = { path = "extern_lib", version = "1.2.0"}
utilitarios = { path = "extern_lib/rust-utilitarios", version = "1.4.2"}

